# Generated by Django 4.2.2 on 2023-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_extractedadvisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedadvisor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
