# Generated by Django 4.2.2 on 2023-07-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_extractedadvisor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedadvisor',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
