# Generated by Django 4.2.2 on 2023-07-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_extractedadvisor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedadvisor',
            name='home_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
